package com.arcane.academy.config;

import com.arcane.academy.model.Boss;
import com.arcane.academy.repository.BossRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

@Component
@RequiredArgsConstructor
@Slf4j
public class BossSeeder {

    private final BossRepository bossRepository;

    public void seed() {
        log.info("Seeding bosses...");

        saveBoss("ch1-boss","The Golem of Types","🗿",1,200,
          "The Golem stirs from its pedestal, stone grinding stone. Its eyes glow cold. \"You claim to know types and values. Demonstrate it.\"",
          "[{\"id\":\"c1q1\",\"type\":\"multiple_choice\",\"question\":\"Which type stores text like \\\"Aldric\\\"?\",\"options\":[\"int\",\"boolean\",\"String\",\"double\"],\"correct\":\"String\",\"explanation\":\"String holds text — sequences of characters. Always wrap String values in double quotes.\"},{\"id\":\"c1q2\",\"type\":\"be_the_compiler\",\"question\":\"What does this print?\\n\\nint x = 10;\\nx += 5;\\nx *= 2;\\nSystem.out.println(x);\",\"options\":[\"10\",\"15\",\"25\",\"30\"],\"correct\":\"30\",\"explanation\":\"x starts at 10. +=5 gives 15. *=2 gives 30.\"},{\"id\":\"c1q3\",\"type\":\"fill_blank\",\"question\":\"Fill the blank to declare a decimal variable:\",\"code\":\"______ mana = 99.5;\",\"correct\":\"double\",\"explanation\":\"double holds decimal numbers.\"},{\"id\":\"c1q4\",\"type\":\"be_the_compiler\",\"question\":\"What does this print?\\n\\nint a = 7;\\nint b = 2;\\nSystem.out.println(a / b);\",\"options\":[\"3.5\",\"3\",\"4\",\"Error\"],\"correct\":\"3\",\"explanation\":\"Integer division drops the decimal. 7/2=3.\"},{\"id\":\"c1q5\",\"type\":\"multiple_choice\",\"question\":\"What does System.out.println(\\\"Hi\\\" + \\\" \\\" + \\\"there\\\") print?\",\"options\":[\"Hi there\",\"Hi + there\",\"Error\",\"Hithere\"],\"correct\":\"Hi there\",\"explanation\":\"The + operator concatenates Strings.\"}]");

        saveBoss("ch2-boss","The Labyrinth Warden","🐺",2,200,
          "The Warden blocks the maze exit. \"Only those who truly understand control flow may leave.\"",
          "[{\"id\":\"c2q1\",\"type\":\"be_the_compiler\",\"question\":\"What prints?\\n\\nint mana = 100;\\nif (mana > 100) {\\n    System.out.println(\\\"Overcharged\\\");\\n} else if (mana == 100) {\\n    System.out.println(\\\"Full\\\");\\n} else {\\n    System.out.println(\\\"Low\\\");\\n}\",\"options\":[\"Overcharged\",\"Full\",\"Low\",\"Nothing\"],\"correct\":\"Full\",\"explanation\":\"100>100 is false. 100==100 is true. Full prints.\"},{\"id\":\"c2q2\",\"type\":\"fill_blank\",\"question\":\"Fill the blank to loop exactly 4 times:\",\"code\":\"for (int i = 0; i __ 4; i++) { }\",\"correct\":\"<\",\"explanation\":\"i<4 runs for 0,1,2,3 — exactly 4 times.\"},{\"id\":\"c2q3\",\"type\":\"be_the_compiler\",\"question\":\"What is printed?\\n\\nint total = 0;\\nfor (int i = 1; i <= 5; i++) {\\n    total += i;\\n}\\nSystem.out.println(total);\",\"options\":[\"5\",\"10\",\"15\",\"20\"],\"correct\":\"15\",\"explanation\":\"1+2+3+4+5=15.\"},{\"id\":\"c2q4\",\"type\":\"multiple_choice\",\"question\":\"A while loop that never changes its condition is called:\",\"options\":[\"A fast loop\",\"An infinite loop\",\"A break loop\",\"A for loop\"],\"correct\":\"An infinite loop\",\"explanation\":\"If the condition never becomes false the loop runs forever.\"},{\"id\":\"c2q5\",\"type\":\"be_the_compiler\",\"question\":\"How many times does 'Go!' print?\\n\\nfor (int i = 10; i > 0; i -= 3) {\\n    System.out.println(\\\"Go!\\\");\\n}\",\"options\":[\"3\",\"4\",\"10\",\"infinite\"],\"correct\":\"4\",\"explanation\":\"i: 10→7→4→1→stop. Runs 4 times.\"}]");

        saveBoss("ch3-boss","The Vault Keeper","🔐",3,250,
          "The Vault Keeper rises from parchment and shadow. \"Prove you understand the discipline of structure.\"",
          "[{\"id\":\"c3q1\",\"type\":\"be_the_compiler\",\"question\":\"What prints?\\n\\nString[] s = {\\\"Fire\\\", \\\"Ice\\\", \\\"Wind\\\"};\\nSystem.out.println(s[1]);\",\"options\":[\"Fire\",\"Ice\",\"Wind\",\"Error\"],\"correct\":\"Ice\",\"explanation\":\"Indices start at 0. s[1] is Ice.\"},{\"id\":\"c3q2\",\"type\":\"fill_blank\",\"question\":\"Fill the blank to get the array length:\",\"code\":\"int[] nums = {1,2,3};\\nSystem.out.println(nums.________);\",\"correct\":\"length\",\"explanation\":\".length returns the number of elements.\"},{\"id\":\"c3q3\",\"type\":\"be_the_compiler\",\"question\":\"What does factorial(4) return?\\n\\nstatic int factorial(int n) {\\n    if (n<=1) return 1;\\n    return n * factorial(n-1);\\n}\",\"options\":[\"4\",\"10\",\"24\",\"Error\"],\"correct\":\"24\",\"explanation\":\"4×3×2×1=24.\"},{\"id\":\"c3q4\",\"type\":\"multiple_choice\",\"question\":\"Key difference between array and ArrayList?\",\"options\":[\"Arrays are faster\",\"Arrays are fixed size; ArrayList resizes\",\"ArrayList is for ints only\",\"No difference\"],\"correct\":\"Arrays are fixed size; ArrayList resizes\",\"explanation\":\"Arrays have fixed size at creation. ArrayList grows dynamically.\"},{\"id\":\"c3q5\",\"type\":\"fill_blank\",\"question\":\"Fill blank to return the sum:\",\"code\":\"static int add(int a, int b) {\\n    ______ a + b;\\n}\",\"correct\":\"return\",\"explanation\":\"The return keyword sends a value back to the caller.\"}]");

        saveBoss("ch4-boss","The Ancient Dragon","🐉",4,300,
          "The Ancient Dragon uncoils from the highest spire. \"Object-oriented mastery is claimed easily. Demonstrate it.\"",
          "[{\"id\":\"c4q1\",\"type\":\"be_the_compiler\",\"question\":\"What prints?\\n\\nclass Animal {\\n    void speak() { System.out.println(\\\"sound\\\"); }\\n}\\nclass Dog extends Animal {\\n    @Override void speak() { System.out.println(\\\"bark\\\"); }\\n}\\nAnimal a = new Dog();\\na.speak();\",\"options\":[\"sound\",\"bark\",\"Error\",\"Nothing\"],\"correct\":\"bark\",\"explanation\":\"Polymorphism: Java uses the actual object type (Dog) at runtime.\"},{\"id\":\"c4q2\",\"type\":\"multiple_choice\",\"question\":\"What calls the parent constructor from a child?\",\"options\":[\"parent()\",\"base()\",\"super()\",\"this()\"],\"correct\":\"super()\",\"explanation\":\"super() calls the parent constructor. Must be first in child constructor.\"},{\"id\":\"c4q3\",\"type\":\"fill_blank\",\"question\":\"Fill the blank:\",\"code\":\"class BattleMage ______ Wizard { }\",\"correct\":\"extends\",\"explanation\":\"extends establishes inheritance.\"},{\"id\":\"c4q4\",\"type\":\"multiple_choice\",\"question\":\"What makes a field 'private'?\",\"options\":[\"It deletes the field\",\"Only code inside the class can access it directly\",\"It becomes read-only\",\"It speeds up access\"],\"correct\":\"Only code inside the class can access it directly\",\"explanation\":\"private restricts direct access. External code must use getters and setters.\"},{\"id\":\"c4q5\",\"type\":\"multiple_choice\",\"question\":\"An abstract class differs from an interface because:\",\"options\":[\"Abstract classes can have concrete methods\",\"Interfaces are faster\",\"Abstract classes can only be used once\",\"No difference\"],\"correct\":\"Abstract classes can have concrete methods\",\"explanation\":\"Abstract classes can mix abstract and concrete methods, and have constructors.\"}]");

        saveBoss("ch5-boss","The Archmage","⚡",5,400,
          "The Archmage regards you with ancient eyes. \"You have walked from Hello World to design patterns. One final examination before the title is yours.\"",
          "[{\"id\":\"c5q1\",\"type\":\"be_the_compiler\",\"question\":\"What prints?\\n\\ntry {\\n    int x = 10 / 0;\\n} catch (ArithmeticException e) {\\n    System.out.println(\\\"caught\\\");\\n} finally {\\n    System.out.println(\\\"done\\\");\\n}\",\"options\":[\"caught\",\"done\",\"caught then done\",\"Error\"],\"correct\":\"caught then done\",\"explanation\":\"The catch block runs, then finally always runs.\"},{\"id\":\"c5q2\",\"type\":\"fill_blank\",\"question\":\"Fill the blank to create a lambda doubler:\",\"code\":\"Function<Integer,Integer> doubler = n __ n * 2;\",\"correct\":\"->\",\"explanation\":\"-> is the lambda arrow operator.\"},{\"id\":\"c5q3\",\"type\":\"multiple_choice\",\"question\":\"What does stream.filter(n -> n > 5) do?\",\"options\":[\"Deletes elements > 5\",\"Keeps only elements > 5\",\"Counts elements > 5\",\"Sorts elements\"],\"correct\":\"Keeps only elements > 5\",\"explanation\":\"filter() keeps elements where the predicate returns true.\"},{\"id\":\"c5q4\",\"type\":\"multiple_choice\",\"question\":\"The Singleton pattern ensures:\",\"options\":[\"Fast creation\",\"Only one instance exists\",\"Immutability\",\"Thread safety\"],\"correct\":\"Only one instance exists\",\"explanation\":\"Singleton restricts instantiation to one object.\"},{\"id\":\"c5q5\",\"type\":\"fill_blank\",\"question\":\"Fill the blank for a generic class:\",\"code\":\"class Box<__> { __ item; }\",\"correct\":\"T\",\"explanation\":\"T is the conventional name for a type parameter.\"}]");

        saveBoss("ch6-boss","The Project Examiner","📋",6,400,
          "The Project Examiner reviews your Task Manager with a critical eye. \"I've seen a thousand half-finished projects. Let's see if yours holds up to real questions.\"",
          "[{\"id\":\"c6q1\",\"type\":\"multiple_choice\",\"question\":\"Why should Task fields be private rather than public?\",\"options\":[\"Private fields run faster\",\"To prevent invalid values being set directly from outside the class\",\"Java requires it\",\"Private fields use less memory\"],\"correct\":\"To prevent invalid values being set directly from outside the class\",\"explanation\":\"Encapsulation protects data integrity. If id were public, anything could change it to -1. With private + a getter, only valid access is possible.\"},{\"id\":\"c6q2\",\"type\":\"be_the_compiler\",\"question\":\"What does the ternary operator produce here?\\n\\nboolean done = true;\\nString status = done ? \\\"[DONE]\\\" : \\\"[OPEN]\\\";\\nSystem.out.println(status);\",\"options\":[\"[OPEN]\",\"[DONE]\",\"true\",\"Error\"],\"correct\":\"[DONE]\",\"explanation\":\"The ternary operator evaluates the condition before ?. If true it returns the first value, if false the second. done is true so [DONE] is returned.\"},{\"id\":\"c6q3\",\"type\":\"fill_blank\",\"question\":\"Fill the blank to check if a list is empty before processing:\",\"code\":\"if (tasks.______() == 0) {\\n    System.out.println(\\\"No tasks\\\");\\n}\",\"correct\":\"size\",\"explanation\":\"ArrayList uses .size() to return its element count, unlike arrays which use .length.\"},{\"id\":\"c6q4\",\"type\":\"multiple_choice\",\"question\":\"What is a 'static' field like nextId used for in the Task class?\",\"options\":[\"It makes the field faster\",\"It belongs to the class itself and is shared across all instances\",\"It prevents the field from being changed\",\"It makes the field accessible from other classes\"],\"correct\":\"It belongs to the class itself and is shared across all instances\",\"explanation\":\"A static field exists once per class, not once per object. All Task objects share nextId, so each new task automatically gets a unique ID.\"},{\"id\":\"c6q5\",\"type\":\"be_the_compiler\",\"question\":\"If you add 3 tasks then call completeTask(99), what happens with this defensive implementation?\\n\\nvoid completeTask(int id) {\\n    boolean found = false;\\n    for(int i=0; i < tasks.size(); i++) {\\n        if(tasks.get(i).getId() == id) {\\n            tasks.get(i).complete();\\n            found = true;\\n        }\\n    }\\n    if(!found) System.out.println(\\\"Task \\\" + id + \\\" not found\\\");\\n}\",\"options\":[\"Crash with exception\",\"Print 'Task 99 not found'\",\"Do nothing silently\",\"Complete all tasks\"],\"correct\":\"Print 'Task 99 not found'\",\"explanation\":\"found stays false because no task has ID 99. After the loop, !found is true so the error message prints. This is defensive programming.\"}]");

        saveBoss("ch7-boss","The Senior Engineer","💼",7,500,
          "The Senior Engineer leans back in her chair. 'I don't care about perfect answers. I care about how you think. Let's find out.'",
          "[{\"id\":\"c7q1\",\"type\":\"multiple_choice\",\"question\":\"What does the % operator return?\",\"options\":[\"The quotient of division\",\"The remainder after division\",\"The square root\",\"The absolute value\"],\"correct\":\"The remainder after division\",\"explanation\":\"% is the modulo operator. 10 % 3 = 1 because 10 / 3 = 3 remainder 1. It's used constantly for divisibility checks.\"},{\"id\":\"c7q2\",\"type\":\"be_the_compiler\",\"question\":\"What does isPalindrome(\\\"a\\\") return?\\n\\nstatic boolean isPalindrome(String s) {\\n    int l=0, r=s.length()-1;\\n    while(l < r) {\\n        if(s.charAt(l) != s.charAt(r)) return false;\\n        l++; r--;\\n    }\\n    return true;\\n}\",\"options\":[\"true\",\"false\",\"Error\",\"null\"],\"correct\":\"true\",\"explanation\":\"For a single character, l=0 and r=0. The condition l < r is immediately false so the loop never runs. return true is reached directly.\"},{\"id\":\"c7q3\",\"type\":\"fill_blank\",\"question\":\"Fill the blank to check if a HashMap contains a key:\",\"code\":\"if (map.____________(word)) { ... }\",\"correct\":\"containsKey\",\"explanation\":\"containsKey(key) returns true if the map has an entry with that key. It's the standard way to check before getting or updating a value.\"},{\"id\":\"c7q4\",\"type\":\"multiple_choice\",\"question\":\"Why is an in-place array reversal better than creating a second array?\",\"options\":[\"It's faster to execute\",\"It uses O(1) extra memory instead of O(n)\",\"It's easier to code\",\"Java requires it\"],\"correct\":\"It uses O(1) extra memory instead of O(n)\",\"explanation\":\"In-place algorithms use a constant amount of extra space regardless of input size. Creating a second array needs space proportional to the input — O(n). Interviewers value memory efficiency.\"},{\"id\":\"c7q5\",\"type\":\"multiple_choice\",\"question\":\"What is the average time complexity of HashMap.get() and HashMap.put()?\",\"options\":[\"O(n)\",\"O(log n)\",\"O(1)\",\"O(n²)\"],\"correct\":\"O(1)\",\"explanation\":\"Hash maps use a hash function to map keys directly to memory positions, so get and put are constant time on average — the same speed whether the map has 10 or 10 million entries.\"}]");

        log.info("Seeded {} bosses.", bossRepository.count());
    }

    private void saveBoss(String id, String name, String glyph, int chapter,
                          int xp, String intro, String questions) {
        bossRepository.save(Boss.builder()
            .id(id).name(name).glyph(glyph).chapterNumber(chapter)
            .xpReward(xp).intro(intro).questionsJson(questions)
            .build());
    }
}
