-- V8: Expand practice_type check constraint to include 'R' (WebR/R-WASM practice type).
-- The original constraint was auto-generated by Hibernate before the R enum value was added.
-- We drop and recreate it to include: JAVA, TAILWIND, REACT, SQL, R, NONE.

ALTER TABLE sub_chunks DROP CONSTRAINT IF EXISTS sub_chunks_practice_type_check;

ALTER TABLE sub_chunks
    ADD CONSTRAINT sub_chunks_practice_type_check
        CHECK (practice_type IN ('JAVA', 'TAILWIND', 'REACT', 'SQL', 'R', 'NONE'));
