/**
 * MermaidBlock — renders a Mermaid diagram from a source string.
 *
 * ## Usage (inline component)
 * ```tsx
 * <MermaidBlock chart="graph TD\n  A --> B" />
 * ```
 *
 * ## Usage (DOM hydration)
 * The `useMermaidHydration(containerRef)` hook post-processes a rendered HTML
 * container and converts every `<code class="language-mermaid">` block into an
 * inline SVG.  Wire it up in pages that render lesson HTML via
 * `dangerouslySetInnerHTML`.
 *
 * ```tsx
 * const ref = useRef<HTMLDivElement>(null)
 * useMermaidHydration(ref)
 * return <div ref={ref} dangerouslySetInnerHTML={{ __html: html }} />
 * ```
 */

import React, { useEffect, useRef, useState } from 'react'
import type { MutableRefObject } from 'react'
import mermaid from 'mermaid'

// Initialise mermaid once on module load — dark theme to match the Academy palette.
mermaid.initialize({
  startOnLoad: false,
  theme: 'dark',
  themeVariables: {
    background: 'transparent',
    primaryColor: '#7c3aed',
    primaryTextColor: '#e2e8f0',
    primaryBorderColor: '#4c1d95',
    lineColor: '#a78bfa',
    secondaryColor: '#1e1b4b',
    tertiaryColor: '#0f0c1a',
  },
  fontFamily: 'inherit',
})

let _uid = 0
function nextId() {
  return `mermaid-${Date.now()}-${_uid++}`
}

// ── Standalone component ─────────────────────────────────────────────────────

interface MermaidBlockProps {
  /** Raw Mermaid diagram source. */
  chart: string
  className?: string
}

/**
 * Standalone component that renders a single Mermaid diagram.
 * Displays a subtle error message if the diagram fails to parse.
 */
export function MermaidBlock({ chart, className }: MermaidBlockProps) {
  const [svg, setSvg] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)
  const id = useRef(nextId())

  useEffect(() => {
    let cancelled = false
    setError(null)

    mermaid.render(id.current, chart)
      .then(({ svg: rendered }) => {
        if (!cancelled) setSvg(rendered)
      })
      .catch((err: unknown) => {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : 'Diagram render error')
        }
      })

    return () => { cancelled = true }
  }, [chart])

  if (error) {
    return (
      <pre className={`text-xs text-red-400 border border-red-800 rounded p-2 overflow-x-auto ${className ?? ''}`}>
        {error}
      </pre>
    )
  }

  if (!svg) {
    return (
      <div className={`h-16 flex items-center justify-center text-muted text-sm ${className ?? ''}`}>
        <span className="animate-pulse">Rendering diagram…</span>
      </div>
    )
  }

  return (
    <div
      className={`mermaid-diagram overflow-x-auto ${className ?? ''}`}
      // SVG is generated by mermaid — safe to set as innerHTML
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  )
}

// ── DOM hydration hook ───────────────────────────────────────────────────────

/**
 * Post-processes a container that holds lesson HTML rendered via
 * `dangerouslySetInnerHTML` and replaces every `<code class="language-mermaid">`
 * block with an inline Mermaid SVG.
 *
 * The hook is a no-op when the container has no mermaid blocks, so it is safe
 * to attach to every lesson section without performance concern.
 *
 * @param containerRef  React ref pointing at the container element.
 * @param deps          Optional extra dependencies that trigger re-hydration
 *                      when the HTML content changes.
 */
export function useMermaidHydration(
  containerRef: MutableRefObject<HTMLElement | null>,
  deps: unknown[] = [],
) {
  useEffect(() => {
    const container = containerRef.current
    if (!container) return

    const codeBlocks = container.querySelectorAll<HTMLElement>('code.language-mermaid')
    if (codeBlocks.length === 0) return

    let cancelled = false

    const renders = Array.from(codeBlocks).map(async (block, i) => {
      const source = block.textContent ?? ''
      const wrapperEl = block.closest('pre') ?? block.parentElement
      if (!wrapperEl || !source.trim()) return

      const id = `mermaid-hydrated-${Date.now()}-${i}`
      try {
        const { svg } = await mermaid.render(id, source)
        if (cancelled) return
        const div = document.createElement('div')
        div.className = 'mermaid-diagram overflow-x-auto'
        div.innerHTML = svg
        wrapperEl.replaceWith(div)
      } catch (err) {
        // Leave the original <pre><code> block intact on failure.
        console.warn('[MermaidHydration] Render error for block', i, err)
      }
    })

    Promise.all(renders).catch(() => { /* silently ignored */ })

    return () => { cancelled = true }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [containerRef, ...deps])
}

export default MermaidBlock
