spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    root: WARN
    com.arcane.academy: INFO
    com.arcane.academy.runner.com.ambravate.polymath.academy.runner.JavaCodeRunner: INFO
    com.arcane.academy.service: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
